#include <stdio.h> //INCLUI TAMBÉM AS FUNÇOES DE ENTRADA E SAIDA
main() //O PROGRAMA COMEÇA AQUI
{ // INICIO DO BLOCO DE INSTRUÇÕES
printf("Hello World"); // ESCREVE A STRING "HELLO WORLD" USANDO A FUNÇÃO PRINTF
}// FIM DO BLOCO DE INSTRUÇÕES(E FIM DO PROGRAMA)
